// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: color.proto

package grpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CurrentColor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color string `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *CurrentColor) Reset() {
	*x = CurrentColor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_color_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrentColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentColor) ProtoMessage() {}

func (x *CurrentColor) ProtoReflect() protoreflect.Message {
	mi := &file_color_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentColor.ProtoReflect.Descriptor instead.
func (*CurrentColor) Descriptor() ([]byte, []int) {
	return file_color_proto_rawDescGZIP(), []int{0}
}

func (x *CurrentColor) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type NewColor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color string `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *NewColor) Reset() {
	*x = NewColor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_color_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewColor) ProtoMessage() {}

func (x *NewColor) ProtoReflect() protoreflect.Message {
	mi := &file_color_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewColor.ProtoReflect.Descriptor instead.
func (*NewColor) Descriptor() ([]byte, []int) {
	return file_color_proto_rawDescGZIP(), []int{1}
}

func (x *NewColor) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

var File_color_proto protoreflect.FileDescriptor

var file_color_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x24, 0x0a, 0x0c, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22,
	0x20, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x32, 0x54, 0x0a, 0x0e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x42, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x6f, 0x72, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x1a,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x2e, 0x4e, 0x65, 0x77,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x67, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_color_proto_rawDescOnce sync.Once
	file_color_proto_rawDescData = file_color_proto_rawDesc
)

func file_color_proto_rawDescGZIP() []byte {
	file_color_proto_rawDescOnce.Do(func() {
		file_color_proto_rawDescData = protoimpl.X.CompressGZIP(file_color_proto_rawDescData)
	})
	return file_color_proto_rawDescData
}

var file_color_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_color_proto_goTypes = []interface{}{
	(*CurrentColor)(nil), // 0: protocolor.CurrentColor
	(*NewColor)(nil),     // 1: protocolor.NewColor
}
var file_color_proto_depIdxs = []int32{
	0, // 0: protocolor.ColorGenerator.GetRandomColor:input_type -> protocolor.CurrentColor
	1, // 1: protocolor.ColorGenerator.GetRandomColor:output_type -> protocolor.NewColor
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_color_proto_init() }
func file_color_proto_init() {
	if File_color_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_color_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrentColor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_color_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewColor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_color_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_color_proto_goTypes,
		DependencyIndexes: file_color_proto_depIdxs,
		MessageInfos:      file_color_proto_msgTypes,
	}.Build()
	File_color_proto = out.File
	file_color_proto_rawDesc = nil
	file_color_proto_goTypes = nil
	file_color_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ColorGeneratorClient is the client API for ColorGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ColorGeneratorClient interface {
	GetRandomColor(ctx context.Context, in *CurrentColor, opts ...grpc.CallOption) (*NewColor, error)
}

type colorGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewColorGeneratorClient(cc grpc.ClientConnInterface) ColorGeneratorClient {
	return &colorGeneratorClient{cc}
}

func (c *colorGeneratorClient) GetRandomColor(ctx context.Context, in *CurrentColor, opts ...grpc.CallOption) (*NewColor, error) {
	out := new(NewColor)
	err := c.cc.Invoke(ctx, "/protocolor.ColorGenerator/GetRandomColor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ColorGeneratorServer is the server API for ColorGenerator service.
type ColorGeneratorServer interface {
	GetRandomColor(context.Context, *CurrentColor) (*NewColor, error)
}

// UnimplementedColorGeneratorServer can be embedded to have forward compatible implementations.
type UnimplementedColorGeneratorServer struct {
}

func (*UnimplementedColorGeneratorServer) GetRandomColor(context.Context, *CurrentColor) (*NewColor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomColor not implemented")
}

func RegisterColorGeneratorServer(s *grpc.Server, srv ColorGeneratorServer) {
	s.RegisterService(&_ColorGenerator_serviceDesc, srv)
}

func _ColorGenerator_GetRandomColor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentColor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColorGeneratorServer).GetRandomColor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocolor.ColorGenerator/GetRandomColor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColorGeneratorServer).GetRandomColor(ctx, req.(*CurrentColor))
	}
	return interceptor(ctx, in, info, handler)
}

var _ColorGenerator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocolor.ColorGenerator",
	HandlerType: (*ColorGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRandomColor",
			Handler:    _ColorGenerator_GetRandomColor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "color.proto",
}
